[package]
name = "wildraccoons"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
driftwood = "0.0.7"
futures = "0.3.30"
log = "0.4.20"
tera = "1.19.1"
tide = "0.16.0"
tide-tera = "0.2.4"
