[package]
name = "wildraccoons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.5"
actix-web = "4.4.1"
async-std = "1.12.0"
env_logger = "0.10.2"
log = "0.4.20"
tera = "1.19.1"
